### Global gh-pages pre-amble
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
encoding: UTF-8
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-coffeescript
  - jekyll-paginate

### The following properties will change on a project-by-project basis

#Google Analytics
google_analytics: UA-93241150-1 #Google analytics code in the format XX-nnnnnnnn-n

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
baseurl: /spring-roo

# Name of the project for display in places like page titles
name: Spring Roo

# ID of the project in the metadata API at spring.io (if this is not a
# valid project ID the javascript widgets in the home page will not work)
project: spring-roo

# Project github URL
github_repo_url: http://github.com/spring-projects/spring-roo

# Project forum URL
#forum: http://forum.spring.io/forum/spring-projects/container

# If you want to include a custom pom.xml or gradle template set these value to true and add _include files
custom_pom_template: false
custom_gradle_template: false


### The following properties are constant for most projects

spring_site_url: https://spring.io
main_site_url: https://springdev.io
projects_site_url: https://projects.springdev.io
questions_url: https://spring.io/questions

# Project Twitter URL
twitter: SpringRoo

# Project Open Graph
url: https://projects.springdev.io/spring-roo
title: Spring Roo Project
description: A next-generation rapid application development tool for Java developers. With Roo you can easily build full Java applications in minutes.
default_bg: default_bg.png

